PKGDIR  ?= ../..
L4DIR   ?= $(PKGDIR)/../..

TARGET        = libc_be_file_rom.a libc_be_file_rom.so
LINK_INCR     = libc_be_file_rom.a
PC_FILENAME   = libc_be_file_rom
REQUIRES_LIBS = libc_be_file
SRC_CC        = rom.cc

include $(L4DIR)/mk/lib.mk
